services:
  - type: web
    name: alley-backend
    env: docker
    plan: free # Use the free instance type
    # Optional: Region can be set if you have a preference (e.g., oregon, frankfurt, ohio, singapore)
    # region: singapore 
    envVars:
      - key: DB_URL
        sync: false # Set to false so Render prompts you to enter it in the dashboard
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true # Render will automatically generate a secure random string for you

