spring.application.name=alley

spring.application.name=jwt

# Global base URL for the entire application
# All your controller endpoints will run under this prefix.
# For example, what used to be localhost:8080/auth/register
# will now be localhost:8080/api/v1/auth/register
server.servlet.context-path=/api/v1/alley
# PostgreSQL Datasource Configuration
# JDBC connection URL: connects to a PostgreSQL database
# named "amigos" running on localhost, port 5332
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/alley}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345678}

# Tells Spring which JDBC driver class to use for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL strategy:
# "create-drop" = create tables on startup, drop them on shutdown.
# Useful for development/testing, but NEVER use in production
# (it deletes all data when the app stops).
# Other options: none, validate, update, create
# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update

# Tells Hibernate to use PostgreSQL-specific SQL dialect
# so it generates optimized SQL for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formats the SQL output in the logs with indentation
# and line breaks for easier reading (instead of one long line)
spring.jpa.properties.hibernate.format_sql=true

# Prints all generated SQL statements to the console/log.
# Useful for debugging queries during development.
spring.jpa.show-sql=true

# Make sure your secret is long and secure (at least 256 bits)
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000
# 1 day in milliseconds


# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:de2b77lkn}
cloudinary.api_key=${CLOUDINARY_API_KEY:751892215834465}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:kiNSoiFnab9Bh-Wqb8XT_ed_vaQ}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Thời gian sống của cache mặc định (e.g. 10 phút tính bằng millis)
spring.cache.redis.time-to-live=600000

# Enable 1-indexed pagination (default is 0-indexed)
spring.data.web.pageable.one-indexed-parameters=true

# Hacker style terminal colors
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){green} %clr(:){faint} %m%n



# Enable/disable the Scalar API reference (default: false)
scalar.enabled=true
# The URL of your OpenAPI document (SpringDoc default)
scalar.url=/api/v1/alley/v3/api-docs
# Optional: Custom path (default: /scalar)
scalar.path=/docs
# Enable actuator support
scalar.actuatorEnabled=true
# Expose the Scalar endpoint
management.endpoints.web.exposure.include=scalar
scalar.theme=laserwave